os:
  - linux
  - osx
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update && sudo apt-get install -y libfuse-dev pkg-config; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install pkg-config && brew tap homebrew/cask && brew cask install osxfuse; fi
script:
  - cargo build --all --all-targets
  - cargo test --all
  - cargo doc --all --no-deps
